// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HistoryDetail interface {
	IsHistoryDetail()
}

type History struct {
	ID     string        `json:"id"`
	Detail HistoryDetail `json:"detail"`
}

type HistoryConnection struct {
	Edges []*HistoryEdge `json:"edges"`
	Nodes []*History     `json:"nodes"`
}

type HistoryEdge struct {
	Node   *History `json:"node"`
	Cursor *string  `json:"cursor"`
}

type HistoryEntityA struct {
	ID    *string `json:"id"`
	TextA *string `json:"textA"`
}

func (HistoryEntityA) IsHistoryDetail() {}

type HistoryEntityB struct {
	ID    *string `json:"id"`
	TextB *string `json:"textB"`
}

func (HistoryEntityB) IsHistoryDetail() {}
